apiVersion: v2
name: mysql
version: v1.0.0
appVersion: "8.0"
description: "官方MySQL数据库服务"
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
sources:
  - https://github.com/mysql/mysql-server
  - https://hub.docker.com/_/mysql
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: "数据库"
