replicaCount: 1

image:
  imageRegistry: "docker.1ms.run"
  repository: niehaoran/mysql-phpmyadmin
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  mysqlPort: 3306
  phpMyAdminPort: 80

networkLimits:
  enabled: true
  egress: "1M"
  ingress: "1M"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  path: /var/lib/mysql
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "local"

env:
  env1:
    name: MYSQL_ROOT_PASSWORD
    value: "root"
  env2:
    name: MYSQL_DATABASE
    value: "mydb" 