replicaCount: 1

image:
  imageRegistry: "docker.io"
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

networkLimits:
  enabled: true
  egress: "1M"
  ingress: "1M"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  path: /var/lib/mysql
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "local"

env:
  env1:
    name: MYSQL_ROOT_PASSWORD
    value: "root"
  env2:
    name: MYSQL_DATABASE
    value: "mydb"
  env3:
    name: MYSQL_USER
    value: "user"
  env4:
    name: MYSQL_PASSWORD
    value: "password" 