name: 主仓库Helm Charts发布

on:
  push:
    branches:
      - main
    paths:
      - 'charts/stable/**'
  # 保留手动触发选项
  workflow_dispatch:
    inputs:
      branch:
        description: '要处理的分支名称(不包含refs/heads/前缀)'
        required: false
        default: 'main'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debug Directory Structure
        run: |
          echo "查看仓库目录结构"
          find charts -type d | sort
          echo "----------------------------"
          ls -la charts/stable/

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Package Charts
        run: |
          mkdir -p .release
          # 使用递归查找所有的Chart
          find charts/stable -name Chart.yaml | while read chart_yaml; do
            chart_dir=$(dirname "$chart_yaml")
            echo "找到Chart: $chart_dir"
            helm package "$chart_dir" -d .release || echo "打包 $chart_dir 失败"
          done
          
          # 显示打包结果
          echo "打包完成的Charts:"
          ls -la .release/

      - name: Create index.yaml
        run: |
          cd .release
          helm repo index .
          echo "index.yaml内容:"
          cat index.yaml

      - name: Deploy to main Helm Charts branch
        run: |
          # 创建或切换到主Helm分支
          TARGET_BRANCH="helm-main"
          echo "目标分支: $TARGET_BRANCH"
          
          # 尝试切换到目标分支，如果不存在则创建
          git fetch origin $TARGET_BRANCH || true
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            echo "分支 $TARGET_BRANCH 已存在，切换到该分支"
            git checkout $TARGET_BRANCH
            git pull origin $TARGET_BRANCH
            git rm -rf *.tgz index.yaml || true
          else
            echo "创建新分支 $TARGET_BRANCH"
            git checkout --orphan $TARGET_BRANCH
            git rm -rf .
          fi
          
          # 复制打包好的文件
          cp -r .release/* .
          
          # 创建README文件记录所有权信息
          echo "# 主仓库Helm Charts" > README.md
          echo "从main分支生成" >> README.md
          echo "最后更新时间: $(date)" >> README.md
          echo "" >> README.md
          echo "## 使用方法" >> README.md
          echo '```bash' >> README.md
          echo "# 添加此Helm仓库" >> README.md
          echo "helm repo add main-repo https://raw.githubusercontent.com/${{ github.repository }}/$TARGET_BRANCH/" >> README.md
          echo "# 更新仓库" >> README.md
          echo "helm repo update" >> README.md
          echo "# 查看可用charts" >> README.md
          echo "helm search repo main-repo" >> README.md
          echo '```' >> README.md
          
          # 提交并推送
          git add *.tgz index.yaml README.md
          git commit -m "更新主仓库Helm Charts"
          
          # 使用PAT令牌进行推送
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin $TARGET_BRANCH
          
          echo "主仓库Charts已发布到分支: $TARGET_BRANCH"
          echo "主Helm仓库URL:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/$TARGET_BRANCH/" 