name: Create Helm Branch After PR

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  create-helm-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get PR Author
        id: get-author
        run: |
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "PR作者: ${{ github.event.pull_request.user.login }}"
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
          
      - name: Package Charts
        run: |
          mkdir -p .release
          # 使用递归查找所有的Chart
          find charts/stable -name Chart.yaml | while read chart_yaml; do
            chart_dir=$(dirname "$chart_yaml")
            echo "找到Chart: $chart_dir"
            helm package "$chart_dir" -d .release || echo "打包 $chart_dir 失败"
          done
          
          # 显示打包结果
          echo "打包完成的Charts:"
          ls -la .release/

      - name: Create index.yaml
        run: |
          cd .release
          helm repo index .
          echo "index.yaml内容:"
          cat index.yaml
          cd ..
          
      - name: Create or Update Helm Branch
        run: |
          # 设置目标分支名
          TARGET_BRANCH="helm-${{ env.PR_AUTHOR }}"
          echo "目标分支: $TARGET_BRANCH"
          
          # 尝试切换到目标分支，如果不存在则创建
          git fetch origin $TARGET_BRANCH || true
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            echo "分支 $TARGET_BRANCH 已存在，更新分支"
            git checkout $TARGET_BRANCH
            git pull origin $TARGET_BRANCH
            git rm -rf *.tgz index.yaml || true
          else
            echo "创建新分支 $TARGET_BRANCH"
            git checkout --orphan $TARGET_BRANCH
            git rm -rf .
          fi
          
          # 复制打包好的文件
          cp -r .release/* .
          
          # 创建README文件记录所有权信息
          echo "# Helm Repository for ${{ env.PR_AUTHOR }}" > README.md
          echo "Generated from PR: #${{ github.event.pull_request.number }}" >> README.md
          echo "Owner: ${{ env.PR_AUTHOR }}" >> README.md
          echo "Last updated: $(date)" >> README.md
          echo "" >> README.md
          echo "## Usage" >> README.md
          echo '```bash' >> README.md
          echo "# Add this Helm repository" >> README.md
          echo "helm repo add ${{ env.PR_AUTHOR }}-repo https://raw.githubusercontent.com/${{ github.repository }}/$TARGET_BRANCH/" >> README.md
          echo "# Update repositories" >> README.md
          echo "helm repo update" >> README.md
          echo "# List available charts" >> README.md
          echo "helm search repo ${{ env.PR_AUTHOR }}-repo" >> README.md
          echo '```' >> README.md
          
          # 提交并推送
          git add *.tgz index.yaml README.md
          git commit -m "Update Helm charts for user ${{ env.PR_AUTHOR }} from PR #${{ github.event.pull_request.number }}"
          
          # 使用PAT令牌进行推送
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin $TARGET_BRANCH
          
          echo "已为用户 ${{ env.PR_AUTHOR }} 创建/更新Helm分支: $TARGET_BRANCH"
          echo "Helm仓库URL: https://raw.githubusercontent.com/${{ github.repository }}/$TARGET_BRANCH/"
          
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const author = process.env.PR_AUTHOR;
            const targetBranch = `helm-${author}`;
            const repoUrl = `https://raw.githubusercontent.com/${repoOwner}/${repoName}/${targetBranch}/`;
            
            const message = `🎉 已成功创建/更新Helm仓库分支！\n\n` +
                           `- 分支: \`${targetBranch}\`\n` +
                           `- Helm仓库URL: \`${repoUrl}\`\n\n` +
                           `使用以下命令添加此Helm仓库:\n` +
                           `\`\`\`bash\n` +
                           `helm repo add ${author}-repo ${repoUrl}\n` +
                           `helm repo update\n` +
                           `helm search repo ${author}-repo\n` +
                           `\`\`\``;
            
            await github.rest.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: prNumber,
              body: message
            }); 